name: Build with conan

on:
  push:
    paths-ignore:
    - "data/maps/**"

jobs:
  build-cmake:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4

    - name: Install Conan
      uses: turtlebrowser/get-conan@main
      with:
        version: 1.64.1

    - name: Build in release mode
      run: |
        mkdir release
        cd release
        cmake -G "Visual Studio 17 2022" -A x64 -DUSE_CONAN=ON -DCMAKE_BUILD_TYPE=Release -DDOWNLOAD_GTEST=TRUE -DBUILD_TESTS=TRUE -DUSE_LUA=FALSE ..
        cmake --build . --config Release

    - name: Package
      run: |
        cd release
        cmake --build . --config Release --target package
        mkdir artifacts
        mv *.win64.zip artifacts

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: InfclassR-windows-2022
        path: release/artifacts
